### PR TITLE
Fix small typos in geographic names in Russian translation

### PR DESCRIPTION
**Pull request by abalabokhin**

### CODE REVIEW

**Comment by Gitjas** [comment]
Who go the credits for the update to?

**Comment by abalabokhin** [comment]
Probably me and klichko86 from arcanecoast.ru. But we were among the original mod translators, so it is not a big deal.

**Comment by Gitjas** [comment]
Thanks!

**Comment by Gitjas** [comment]
v18 will have some new lines in setup.tra that would need translation (they were in the mod before, just not correctly traify-d):

     /* lines in p#kiv01.baf */
    @108004 = ~Death to the Drow!~
    @108005 = ~In Shevarash name!~
    @108006 = ~Be damned, Lloth's spawn!~
    @108007 = ~For Shevarash!~
    @108008 = ~Doomed be the dark ones!~
    @108009 = ~Vengeance for our fallen!~

**Pull request merged**
